src/Entity/Plane.php
<?php

namespace App\Entity;

use App\Repository\PlaneRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlaneRepository::class)]
class Plane
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $max_passengers = null;

    #[ORM\Column(length: 64)]
    private ?string $company = null;

    #[ORM\Column(length: 64)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMaxPassengers(): ?int
    {
        return $this->max_passengers;
    }

    public function setMaxPassengers(int $max_passengers): self
    {
        $this->max_passengers = $max_passengers;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/PlaneType.php
<?php

namespace App\Form;

use App\Entity\Plane;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlaneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('max_passengers')
            ->add('company')
            ->add('type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Plane::class,
        ]);
    }
}

src/Controller/PlaneController.php
<?php

namespace App\Controller;

use App\Entity\Plane;
use App\Form\PlaneType;
use App\Repository\PlaneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/planes')]
class PlaneController extends AbstractController
{
    #[Route('/', name: 'app_plane_index', methods: ['GET'])]
    public function index(PlaneRepository $planeRepository): Response
    {
        return $this->render('plane/index.html.twig', [
            'planes' => $planeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_plane_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PlaneRepository $planeRepository): Response
    {
        $plane = new Plane();
        $form = $this->createForm(PlaneType::class, $plane);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $planeRepository->save($plane, true);

            return $this->redirectToRoute('app_plane_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('plane/new.html.twig', [
            'plane' => $plane,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_plane_show', methods: ['GET'])]
    public function show(Plane $plane): Response
    {
        return $this->render('plane/show.html.twig', [
            'plane' => $plane,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_plane_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Plane $plane, PlaneRepository $planeRepository): Response
    {
        $form = $this->createForm(PlaneType::class, $plane);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $planeRepository->save($plane, true);

            return $this->redirectToRoute('app_plane_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('plane/edit.html.twig', [
            'plane' => $plane,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_plane_delete', methods: ['POST'])]
    public function delete(Request $request, Plane $plane, PlaneRepository $planeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$plane->getId(), $request->request->get('_token'))) {
            $planeRepository->remove($plane, true);
        }

        return $this->redirectToRoute('app_plane_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/plane/_delete_form.html.twig
<form method="post" action="{{ path('app_plane_delete', {'id': plane.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ plane.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/plane/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/plane/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Plane{% endblock %}

{% block body %}
    <div class="d-flex flex-column align-items-center">
        <h1>Edit Plane</h1>

        {{ include('plane/_form.html.twig', {'button_label': 'Update'}) }}
        {{ include('plane/_delete_form.html.twig') }}
        <a class="btn btn-secondary" href="{{ path('app_plane_index') }}">back to list</a>

        
    </div>
{% endblock %}

templates/plane/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plane index{% endblock %}

{% block body %}
    <h1>Plane index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Max_passengers</th>
                <th>Company</th>
                <th>Type</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for plane in planes %}
            <tr>
                <td>{{ plane.id }}</td>
                <td>{{ plane.name }}</td>
                <td>{{ plane.maxPassengers }}</td>
                <td>{{ plane.company }}</td>
                <td>{{ plane.type }}</td>
                <td>
                    <a href="{{ path('app_plane_show', {'id': plane.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('app_plane_edit', {'id': plane.id}) }}" class="btn btn-warning">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_plane_new') }}" class="btn btn-success">Create new</a>
{% endblock %}

templates/plane/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Plane{% endblock %}

{% block body %}
    <div class="d-flex flex-column align-items-center">
        <h1>Create new Plane</h1>
        {{ include('plane/_form.html.twig') }}
        <a href="{{ path('app_plane_index') }}">back to list</a>
    </div>
{% endblock %}

templates/plane/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plane{% endblock %}

{% block body %}
<div class="d-flex flex-column align-items-center">
    <h1>Plane</h1>

    <table class="table w-50">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ plane.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ plane.name }}</td>
            </tr>
            <tr>
                <th>Max_passengers</th>
                <td>{{ plane.maxPassengers }}</td>
            </tr>
            <tr>
                <th>Company</th>
                <td>{{ plane.company }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ plane.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_plane_index') }}">back to list</a>

    <a href="{{ path('app_plane_edit', {'id': plane.id}) }}">edit</a>

    {{ include('plane/_delete_form.html.twig') }}
</div>
{% endblock %}